### PR TITLE
Extract full text from toc heading elements. 

### LINKED ISSUE #842: Schedule entries in ToC missing <ref> contents
image
image

See https://edit.laws.africa/places/ng/tasks/4484/ on https://edit.laws.africa/documents/3298/

### PR DESCRIPTION
**Pull request by longhotsummer**
Imported from cap95 rtf @ 1980-01-01 2019-11-07 08-42-41

Fixes #842

### CODE REVIEW

**Comment by longhotsummer** [comment]
Whoops, this doesn't fix schedules yet...

**Comment by longhotsummer** [comment]
Schedule titles are calculated from the `FRBRalias` attribute, which is done by Cobalt, so we'll have to make the change there.

**Comment by longhotsummer** [comment]
This is ready to be reviewed for non-schedule headings.

**Comment by goose-life** [comment]
@longhotsummer refs already work for section headings?
image

**Comment by longhotsummer** [comment]
Good point, turns out jquery's `.text()` does this already. Reverted those commits.

**Comment by longhotsummer** [comment]
Imported from cap95 rtf @ 1980-01-01 2019-11-07 11-06-53
Imported from cap95 rtf @ 1980-01-01 2019-11-07 11-06-41

**Pull request merged**
