### PR TITLE
use latest indigo-web (8.1.2)

### PR DESCRIPTION
**Pull request by goose-life**

### CODE REVIEW

**Comment by longhotsummer** [comment]
Unfortunately we still need to import various things directly from this, so the updated indigo-web must also be copied into 
 `indigo_app/static/lib/indigo-web/scss`

🙄

**Comment by goose-life** [comment]
I was surprised by the extent of the changes to the scss but I'm guessing it's just been a while since we needed the latest indigo-web for indigo, so the restructuring hadn't been pulled in?

**Comment by longhotsummer** [comment]
> Wow, yes, it has been ages. Let me see if now is a good time to get rid of that completely...

Everything except PDF exports now uses la-web-components. I'm looking into what we can do for PDF.

**Comment by longhotsummer** [comment]
Let's merge https://github.com/laws-africa/indigo/pull/1495 first, then this should be partially redundant

**Review by longhotsummer — APPROVED** [review]

**Pull request merged**
