### PR TITLE
Indigo Explorer, version 17.2

### PR DESCRIPTION
**Pull request by goose-life**

### CODE REVIEW

**Review by longhotsummer — APPROVED** [review]

**Comment by longhotsummer** [comment]
You'll need to update setup.py to anchor the cobalt dependency at 5 (6.0.0 is what's breaking)

**Review by longhotsummer — APPROVED** [review]

**Comment by goose-life** [comment]
@longhotsummer looks like tests are still failing because of a slaw issue:
`Stderr: /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/slaw-12.0.0/lib/slaw/parse/builder.rb:114: warning: URI.unescape is obsolete`
Does this mean anything to you? It looks as if `uri` is imported at the top of that file (https://github.com/laws-africa/slaw/blob/master/lib/slaw/parse/builder.rb#L3) but I'm not seeing it in gemspec where the treetop version is given. And a search of the code doesn't look as if it's imported from elsewhere within the repo, but I'm not great at reading ruby!

**Comment by longhotsummer** [comment]
Ignore the slaw thing, it's a red herring. I had the other error recently, give me a few...

**Comment by longhotsummer** [comment]
Now that the explorer is in master, can we close this PR?

**Comment by goose-life** [comment]
Dumb question, but deleting the branch won't affect https://github.com/laws-africa/indigo/releases/tag/v17.2.0, right?

**Pull request closed without merging**
