### PR TITLE
Added assigned_to to list and column views for tasks

### PR DESCRIPTION
**Pull request by AliciadW**
screenshot 2019-02-26 at 12 23 19
screenshot 2019-02-26 at 12 23 27

### CODE REVIEW

**Comment by longhotsummer** [comment]
Looks good to me. @goose-life what do you think about having "this task has not been assigned" vs just not showing anything at all?

**Comment by goose-life** [comment]
My inclination would be to have nothing rather – it's already 'open'?

**Comment by goose-life** [comment]
Maybe we eventually want an 'Assign' drop-down in that space?

**Comment by longhotsummer** [comment]
Good idea. @AliciadW if there's no assignee, let's just put nothing for now.

**Comment by AliciadW** [comment]
This has been updated

**Pull request merged**
