### PR TITLE
skip creating amendment tasks on approve

### PR DESCRIPTION
**Pull request by goose-life**
https://www.loom.com/share/3e15e508381943d1854c694fa83db2a8

### CODE REVIEW

**Comment by longhotsummer** [comment]
https://www.loom.com/share/272debbbe534410f8d2db3cb02b4aebc

**Comment by goose-life** [comment]
https://www.loom.com/share/b36b953b53534610809bb317748666ce

**Comment by goose-life** [comment]
watching the feedback now! I like the 'Create' idea

**Comment by goose-life** [comment]
image

**Comment by goose-life** [comment]
image

**Review by longhotsummer — APPROVED** [review]

**Pull request merged**
