### PR TITLE
467 progress task without leaving page

### PR DESCRIPTION
**Pull request by AliciadW**

### CODE REVIEW

**Comment by AliciadW** [comment]
Fixes #467

**Comment by longhotsummer** [comment]
@goose-life These options show up whether or not the user has permissions to do them, right? Which could be confusing... How do the permissions from #490 get used in the view?

**Comment by goose-life** [comment]
@longhotsummer good point! @AliciadW, we probably want to do something similar to the task detail view (`submit_task_permission`, `reopen_task_permission`, etc):
https://github.com/laws-africa/indigo/blob/d557a975dbe40e59dafe2b62a353fcdd6dd1b5e3/indigo_app/templates/indigo_api/task_detail.html#L83

which gets its context here:
https://github.com/laws-africa/indigo/blob/f07ccbaa869e9775283660419614b5ccf9706192/indigo_app/views/tasks.py#L86

will that be fairly simple to pull through?

**Comment by goose-life** [comment]
@longhotsummer should we move all those permissions things into TaskViewBase?

**Comment by longhotsummer** [comment]
> @longhotsummer should we move all those permissions things into TaskViewBase?

The business logic lives in the task, which is great. The permissions need to show up in TaskListView, WorkflowDetailView and TaskDetailView. They don't have a good common ancestor. So either we need a mixin, or we just copy-and-paste the `get_context_data` code:

```python
context['close_task_permission'] = has_transition_perm(task.close, self)
# etc.
```

**Comment by AliciadW** [comment]
@goose-life looking at this now.

**Pull request merged**
