### PR TITLE
don't get rid of fill-in-the-blanks ('-' and '_' increased from 5 to 10)

### PR DESCRIPTION
**Pull request by goose-life**

### CODE REVIEW

**Comment by longhotsummer** [comment]
Why the bump from 5 to 10? If it's all on its own line (surrounded by whitespace), isn't it safe to match fewer?

**Comment by goose-life** [comment]
thanks! fixed. wasn't focusing

**Comment by goose-life** [comment]
see issue #220

**Comment by longhotsummer** [comment]
@goose-life tests are failing (see the travis build links above). Can be useful to run `python manage.py test` before committing, especially on these backend components which have some pretty decent test coverage.

```
======================================================================
FAIL: test_remove_boilerplace (indigo_za.tests.test_importer_za.ImporterZATestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/OpenUpSA/indigo/indigo_za/tests/test_importer_za.py", line 27, in test_remove_boilerplace
    assert_equal(reformatted, "text\n\n\n\n\n\nmore text\n")
AssertionError: u'text\n-------------\n\n\n\n\nmore text\n' != u'text\n\n\n\n\n\nmore text\n'
  text
- -------------
+ 
```

**Pull request merged**
