### PR TITLE
User Tasks View

### LINKED ISSUE #881: as a manager I want to see who is currently working on what
Use case: I'm starting a new municipality and want to get an idea of who has which tasks currently assigned to them.

Suggestion: Include 'Tasks currently assigned to {user}' on their profile, as a separate tab / above 'Recent activity'

### PR DESCRIPTION
**Pull request by ro6ley**
#### What does this PR do?

This PR adds functionality for users to view what other users are working on.

#### Description of Task to be completed?

This PR adds a new tab next to Activity that reads Tasks and includes all the info about that user from whatever is in their 'My tasks' view

#### How should this be manually tested?

- Set up and start indigo.
- Navigate to http://127.0.0.1:8000/contributors/
- Open a user's profile and select the `Tasks` section

#### What are the relevant issues?

closes #881 

#### Screenshots (if appropriate)

User tasks view with tasks:
image

User tasks view with no tasks and no full name:
image

### CODE REVIEW

**Comment by goose-life** [comment]
this looks right, but I wonder, is there a way we can {% include %} a template in  indigo_social/templates/indigo_social/user_tasks as well as in indigo_app/templates/indigo_app/tasks/my_tasks to avoid code duplication? and also change `MyTasksView` in indigo_app/views/tasks to be more generic and use that instead of `UserTasksView`?

**Comment by ro6ley** [comment]
@goose-life I had thought about that, but it meant making a few changes to the `My Tasks` view so that it can look uniform and fit in the profile section. Let me try making it one

**Comment by ro6ley** [comment]
@goose-life I found a workaround regarding the reuse of `MyTasksView` . Only major thing is, the dimensions of the cards are now the same size since the same view is used in the profile. 

This is how My Tasks looks like right now:
image

This is how the same view looked before:
image

You can see the difference in sizes of the columns. I coulnd't maintain the same sizing since the profile view is smaller.

**Comment by goose-life** [comment]
Thanks for looking into this! I don't dislike the cards as equal thirds, but I didn't make that design decision in the first place so I can't overturn it now. I guess GK can decide which he prefers when he's back next year. Would you mind pushing the commit that includes your workaround in the meantime? no rush on that though :)

**Comment by ro6ley** [comment]
@goose-life I have pushed the commits

**Pull request merged**
