### PR TITLE
[Do not merge] Task view

### PR DESCRIPTION
**Pull request by AliciadW**
Screenshot 2019-05-28 at 12 21 54

### CODE REVIEW

**Comment by AliciadW** [comment]
@longhotsummer I've broken the card out as a component and added it to `_task_cards.html`. Let me know your thoughts on this.

**Comment by longhotsummer** [comment]
Looks good to me (I haven't tested it).

We should now be able to use that template in `_task_cards.html`.

**Comment by longhotsummer** [comment]
Oh, sorry, you're already doing that!

**Comment by longhotsummer** [comment]
@AliciadW Happy for you to merge this when you're ready.

**Pull request merged**
