### PR TITLE
Merge work changes with activities.

### LINKED ISSUE #333: As a user looking at the work page, I want to see recent activity
Help the user differentiate or understand the difference between recent changes, and recent activity.

Can they be merged into one timeline? Can we link changes (diffs) to activity entries?

Probably show recent things, then click through to a full paginated listing.

### PR DESCRIPTION
**Pull request by longhotsummer**
Closes #333

changes cpt muni planning laws africa 2019-02-05 17-17-02

### CODE REVIEW

**Comment by goose-life** [comment]
1. if I've understood right, this is just going to double up every time: 'Person updated Work X time ago'; AND '(same) Person made N changes (almost same) X time ago' – what's the benefit in also including the activity stream sentences?
2. 'Restore this version' seems to be giving the more up-to-date version as the option to restore?

I wonder if it would be better just to leave the activity stream out of `/revisions` and link to it from the place's activity tab whenever a work has been updated?

**Comment by longhotsummer** [comment]
I thought it might be useful to see what *changed* when it says "Greg update this work...", which is why I tried to merge the views.

What do you think about automatically combining "updated" activity and the "X changes" items when they're, say, within 5 seconds of each other (ie. the one caused the other)?

Another option is to keep them totally separate, and then provide a link from "Greg updated" to the (probably) appropriate version change in the changes view? I do see that maybe the revision history and reverting changes functionality deserves a specific view.

**Comment by goose-life** [comment]
I agree that it would be good to know what changed, but then the fact that the work was updated becomes redundant I think, so we can just display the X changes? especially in the `/revisions` view, but I don't see why it shouldn't also be in `/activities` – it's autocollapsed so won't take up any more space than it currently does. 
but maybe we should keep the 'revert' stuff out of `/activity`?

**Comment by longhotsummer** [comment]
I think I'm leaning towards a combined `/revisions` and `/activity` view, and skipping "updated" activities in lieu of the changes themselves. I'm worried that separate views would be confusing -- when should the user look at one rather than the other? They're both showing historical activity. The bulk of the activities will be changes.

**Comment by goose-life** [comment]
> I think I'm leaning towards a combined `/revisions` and `/activity` view, and skipping "updated" activities in favour of the changes themselves.

I think we're on the same page here.

Do you mean by 'separate views' that it would look different on the Work's Activity page vs the Place's? If yes then I agree there too, there's no reason to have it be different. It would just be weird for someone to want to revert to a previous version of a work from what's essentially the Place overview I think, so I would like to make a case for that only being included in the Work's Activity view.

**Comment by longhotsummer** [comment]
> Do you mean by 'separate views' that it would look different on the Work's Activity page vs the Place's? If yes then I agree there too, there's no reason to have it be different. It would just be weird for someone to want to revert to a previous version of a work from what's essentially the Place overview I think, so I would like to make a case for that only being included in the Work's Activity view.

No, I mean that there's a work `/activity` page and a work `/revisions` page. I prefer a combined page (which we're in agreement with).

I'm not suggesting we include work revisions anywhere else in activity views (eg. the place activity page).

In think we're in agreement. I'll go ahead and make the tweaks to essentially remove the "updated" activity.

**Comment by goose-life** [comment]
totally on the same page

**Comment by longhotsummer** [comment]
changes example with another change indigo platform 2019-02-06 13-52-52

**Comment by goose-life** [comment]
Nice!

**Pull request merged**
