### PR TITLE
create Amendment tasks on approve when a work amends other works

### PR DESCRIPTION
**Pull request by goose-life**
https://www.loom.com/share/ce9c3ea78da9448a8bfe0085800dd98e?sid=370dd8e1-10c2-4c59-aef8-883b68dd58ed

https://www.loom.com/share/0b0a04dc32ba44d6bbbe4b7410cb467b?sid=88932af7-6bf8-46f9-98fb-39cc7950c439

### CODE REVIEW

**Comment by goose-life** [comment]
One consequence of doing the amendments made tasks after the passive ones is that those descriptions will overwrite the others, in the case of both the amended and the amending work being approved in the same batch.

I think that's fine, but if we wanted to be fancier about it we could join all the amendments and do them once, something like
**Amendment tasks will be created**
- Amending work
  - Amended work
    - Task description
  - Amended work
    - Task description
  - Amended work
    - Task description
----------------------
- Amending work
  - Amended work
    - Task description
----------------------
etc?

**Comment by goose-life** [comment]
I actually don't think the above is being too fancy — it's weird to potentially show the same task twice and only have one of the edits take effect.
And I thought the odds of this happening would be low in reality, but actually it's very easy to imagine someone doing research from a consolidation, creating a principal work and recording all the amendments on it (as well as creating stubs of all the amending works), and then approving them all in one go.

**Comment by goose-life** [comment]
Scenario 1: a group of amended and amending WIPs are signed off together, but the tasks are only edited once
https://www.loom.com/share/5292819902b4425a921175e47af5ef18?sid=8940c670-6800-4ad7-8895-2aa76777ed06

Scenario 2: a new WIP amends an existing approved work, and only the new amendment tasks are created
https://www.loom.com/share/b2db0fd7fd5e4f9c9e75f7f8008dea91?sid=687e46a1-1b6b-4873-b445-2d407b34d52f

**Review by longhotsummer — COMMENTED** [review]
I expected to see more template changes in this PR, am I missing something?

**Comment by goose-life** [comment]
> I expected to see more template changes in this PR, am I missing something?

you're not! the actual change is what goes into `amendments_per_work` — but the way it's displayed is what we had before

**Comment by goose-life** [comment]
list groups (WIP)
https://www.loom.com/share/0dd388867f72421abb774cb6f29a9d54?sid=e70b4f19-1c10-4595-a2f5-069005badc06

**Comment by goose-life** [comment]
@longhotsummer 
https://www.loom.com/share/adaa916ce28f43aea6cfeb509281ac6f?sid=62925f97-6ce3-4e87-a681-7353fcf6b1dd

**Comment by goose-life** [comment]
actually 😂 
https://www.loom.com/share/37847f687d034a70a121189b12acfe64?sid=28223550-9c34-47f0-9a73-50c12b2081d2

**Review by longhotsummer — APPROVED** [review]
looks good

**Pull request merged**
