### PR TITLE
Updated parent work to primary in template - NOT CODE

### LINKED ISSUE #566: Change 'parent work' to 'primary work'

### PR DESCRIPTION
**Pull request by AliciadW**
Closes #566

### CODE REVIEW

**Comment by longhotsummer** [comment]
@goose-life do any changes need to be made to the spreadsheet?

**Comment by goose-life** [comment]
@longhotsummer yep! just not before it's been deployed (especially for KL)

**Comment by longhotsummer** [comment]
Ok, will deploy now.

**Comment by goose-life** [comment]
actually, yes, but there are more changes needed:
https://github.com/laws-africa/indigo/blob/4bbbbedfd2e30fa2dc7790482173330cae9b3521/indigo_app/views/works.py#L655-L674
https://github.com/laws-africa/indigo/blob/4bbbbedfd2e30fa2dc7790482173330cae9b3521/indigo_app/views/works.py#L748-L756
https://github.com/laws-africa/indigo/blob/4bbbbedfd2e30fa2dc7790482173330cae9b3521/indigo_app/views/works.py#L784

**Comment by goose-life** [comment]
@longhotsummer alternatively we don't make the changes above but then the spreadsheet will have to stay as 'parent_work'

**Comment by longhotsummer** [comment]
I don't mind if internally it's called `parent_work`. If we're going to change `parent` to `primary` in the spreadsheet (which I think we should do), we should do it now (before we have many spreadsheets) and then update the spreadsheets when we deploy.

**Comment by goose-life** [comment]
cool, then the minimum that needs to change is
https://github.com/laws-africa/indigo/blob/4bbbbedfd2e30fa2dc7790482173330cae9b3521/indigo_app/views/works.py#L655-L656

**Comment by longhotsummer** [comment]
@goose-life https://github.com/laws-africa/indigo/pull/613

**Pull request merged**
