### PR TITLE
add 'Submitted by' filter to task list view

### PR DESCRIPTION
**Pull request by goose-life**
front end is not looking too hot
image

### CODE REVIEW

**Comment by goose-life** [comment]
@AliciadW not sure of your current availability but if you're free for something little I think something needs to change either here:
https://github.com/laws-africa/indigo/blob/f59587f4da3109fa4c722a2b954135780a237eeb/indigo_app/templates/indigo_api/task_list.html#L12-L13
or here:
https://github.com/laws-africa/indigo/blob/434cc0229278a7bc74295d57845601f7f293450a/indigo_app/templates/indigo_api/_task_filter_form.html#L4
to fit all the buttons comfortably (see screenshot above of 8000/places/na/tasks/).

**Comment by AliciadW** [comment]
@goose-life No problem :-)
I'll have a look at this today.

**Comment by AliciadW** [comment]
@goose-life I have reduced the width of the dropdown button by 20px; let me know if this is acceptable. An alternative is to move the list/card view button and create task button below the filters.

**Comment by goose-life** [comment]
looks good to me, thanks @AliciadW! 
image

**Pull request merged**
